### ISSUE TITLE
SignupUserInput is defined twice in schema.graphql

### ISSUE THREAD

**Issue by kbrandwijk** [howtographql/react-relay#4]
Causing an error on initial run. Removed the one without the `authProvider` field, now it's working.

**Comment by idkjs** [comment]
This is the error in the console for the above issue

```
$ relay-compiler --src ./src --schema ./schema.graphql
HINT: pass --watch to keep watching for changes.
Parsed default in 0.01s

Writing default
ERROR:
Error loading schema. Expected the schema to be a .graphql or a .json
file, describing your GraphQL server's API. Error detail:

Error: Type "SignupUserInput" was defined more than once.
    at buildASTSchema (/Users/shingdev/.config/yarn/global/node_modules/graphql/utilities/buildASTSchema.js:111:17)
    at _getSchema (/Users/shingdev/.config/yarn/global/node_modules/relay-compiler/bin/relay-compiler:222:13)
    at Object.getSchema (/Users/shingdev/.config/yarn/global/node_modules/relay-compiler/bin/relay-compiler:103:19)
    at CodegenRunner.<anonymous> (/Users/shingdev/.config/yarn/global/node_modules/relay-compiler/bin/relay-compiler:5237:53)
    at Generator.next (<anonymous>)
    at step (/Users/shingdev/.config/yarn/global/node_modules/relay-compiler/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/shingdev/.config/yarn/global/node_modules/relay-compiler/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise (<anonymous>)
    at F (/Users/shingdev/.config/yarn/global/node_modules/core-js/library/modules/_export.js:35:28)
    at CodegenRunner.<anonymous> (/Users/shingdev/.config/yarn/global/node_modules/relay-compiler/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)

```
